---
title: "HW_A4"
author: "Yuhang Zhu"
date: "2023-10-06"
output: github_document
---

### 9.4 EXERCISES

#### 1
> The **objectiv**e account is based on theory or observations from data, whereas the **subjective** account concerns the beliefs of human beings

1a: objective

1b: subjective

1c: objective

1d: subjective

1e: objective

#### 2
> 
There are two types of **objective probability**, classical and empirical.  
- The **classical account** focuses on the ratio of an outcome to all possible outcomes.  
- The **empirical account** focuses on the ratio of the frequency with which a given outcome actually occurs relative to all other outcomes that occur.

> **Subjective probability** is based on people’s expertise (or lack thereof) and judgments “and is basically an educated guess as to the chances of an event occurring”

2a: empirical

2b: subjective

2c: empirical

#### 3
>
- A **simple event** is a single outcome that we represent as having occurred to an individual or group.  
- A **compound event** is composed of two or more simple events; we can break it down into constituent parts.

3a: simple

3b: simple

3c: compound

3d: compound

3e: compound

#### 4
> 
- Two events are **independent** if the probability that one occurs does not change as a consequence of the other event’s occurring.
- Two events are **mutually exclusive** when one cannot occur if the other has occurred.
- **Collective exhaustivity** is the characteristic that each and every event ﬁts into at least one of the categories.

4a: independent

4b: mutually exclusive and collectively exhaustive

4c: independent

4d: mutually exclusive and collectively exhaustive

4e: mutually exclusive and collectively exhaustive

#### 5
> 
A **joint probability** is the probability of a compound event.  
- If the simple events of a compound event are **independent**, then their joint probability is the product of the probabilities of each simple event.  
- The joint probability of two **mutually exclusive** events is the sum of the simple probabilities.

5a: true

5b: false

5c: true

#### 6
> It should be apparent to you that the joint probability of a set of mutually exclusive, collectively exhaustive events is 1.0, since just events make up the entire sample space.

Pr(a ∪ b) = 1

#### 7
Pr(a ∪ d) = `r 0.23 + (1 - 0.23 - 0.15 - 0.46)`

#### 8
Pr(a ∩ b ∩ c ∩ d) = 0

#### 9
Pr(a ∩ b) = `r 0.13 * 0.36`

#### 10
> 
- Pr(A ∩ B) = Pr(B|A)Pr(A) = Pr(A|B)Pr(B)  
- When A and B are independent, Pr(A|B) = Pr(A) and Pr(B|A) = Pr(B), and this rule reduces to Pr(A ∩ B) = Pr(A)Pr(B).
- Pr(A ∪ B) = Pr(A) + Pr(B) − Pr(A ∩ B)

Pr(A ∪ B) = Pr(A) + Pr(B) − Pr(A ∩ B) = Pr(A) + Pr(B) - Pr(A)Pr(B)

P(B) = (Pr(A ∪ B) - Pr(A)) / (1 - P(A))= `r (0.5 - 0.3) / (1 - 0.3)`

#### 11
P(B) = `r (0.6 - 0.3) / (1 - 0.4)`

#### 12
P(B) = `r (0.6 - 0.4) / (1 - 0.4)`

#### 13
> 
See, p.184

13a: `r format(factorial(12) / factorial(7), scientific = F)` 

13b: `r factorial(5) / factorial(6)` 

13c: `r factorial(12) / (factorial(5) * factorial(7))`

13d: `r factorial(7) / (factorial(2) * factorial(5))`

13e: `r format(factorial(12) / factorial(7), scientific = F)`

13f: `r factorial(7) / factorial(5)`

#### 14
`r (factorial(6) / (factorial(2) * factorial(4))) * (factorial(5) / (factorial(2) * factorial(3))) * (factorial(4) / (factorial(1) * factorial(3)))`

#### 15
`r factorial(6) / factorial(0)`

#### 16

16a: `r factorial(15) / (factorial(6) * factorial(9))`

16b: `r (factorial(10) / (factorial(3) * factorial(7))) * (factorial(5) / (factorial(3) * factorial(1)))`

16c: `r (factorial(10) / (factorial(4) * factorial(6))) * (factorial(5) / (factorial(2) * factorial(3)))`

#### 17
(C(4 1) * 3^3^) / (4^4^) = `r (factorial(4) / (factorial(1) * factorial(3)) * 3^3) / (4^4)`

#### 18
(C(5 2) * 3^3^) / (4^5^) = `r (factorial(5) / (factorial(2) * factorial(3)) * 3^3) / (4^5)`

#### 19
Pr(7) = 6/36 = 1/6

Pr(3) = 2/36 = 1/18

#### 20
February: Pr(f|I~r~) = `r (0.3 * 0.5) / (0.3 * 0.5 + 0.7 * 0.5)` 0.3

March: Pr(f|I~r~) = `r (0.8 * 0.3) / (0.8 * 0.3 + 0.2 * 0.7)` 0.63

April: Pr(f|I~r~) = `r (0.1 * 0.63) / (0.1 * 0.63 + 0.9 * 0.27)` 0.21

#### 21
link is unavailable.

#### 22
We should always switch doors.

When you choose a door, the chance you choose the car is 1/3 and choose the goat is 2/3.

Then Monte will open a door with a goat behind it. 

If you switch, the chance you win the car will be 2/3. 

Because if you choose the goat initially (= 2/3), you will always win the car. If you choose the car initially (= 1/3), you will lose the car.

#### 23

23a: `r (0.3 * 0.5) + (0.3 * 0.4) + (0.4 * 0.3)`

23b: `r (0.3 * 0.5) / ((0.3 * 0.5) + (0.3 * 0.4) + (0.4 * 0.3))`

23c: `r (0.3 * 0.4) / ((0.3 * 0.5) + (0.3 * 0.4) + (0.4 * 0.3))`

23d: `r (0.4 * 0.3) / ((0.3 * 0.5) + (0.3 * 0.4) + (0.4 * 0.3))`

#### 24
> The odds of an event is deﬁned as the ratio of the probability of the event’s occurring and the probability that it does not occur: Pr(y) / Pr(∼y).

odds = `r 0.62 / 0.38`

#### 25
> [Pr(x~1~)/Pr(∼x~1~)] / [(]Pr(x~2~)/Pr(∼x~2~)]

odds ratio = `r (3/1) / (1/2)`

#### 26
An unemployed person is 2.42 times more likely to vote for the National Front in French election as an employed person. 

An unemployed person is 142% more likely to vote for the National Front in French election as an employed person.

A person with a college degree is 0.38 times as likely to vote for the National Front compared to those who did not complete high school.

A person with a college degree is 62% less likely to vote for the National Front compared to those who did not complete high school.